spring:
    
    datasource:
        url: jdbc:mariadb://localhost:3307/oauth?autoReconnect=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: ahqk!dlfdl1
        driver-class-name: org.mariadb.jdbc.Driver
        
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            hibernate:
                ddl-auto: update
            properties:
                hibernate:
                    format_sql: true
                    show_sql: true
            defer-datasource-initialization: true
            
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 12680540130-23fk76rgsa5nr0p3gc5675mp1ker1oov.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile, email
                        
                    naver:
                        client-id: UiYD5JXHHLOPxzoGh5ZR
                        client-secret: fAtiBKCnj9
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        scope: email, nickname
                        client-name: Naver
                        
                    kakao:
                        client-id: 3898b44c885bf5f1da240359a0d654f4
                        client-secret: UhKzWfNhM8SdBJwGvyLUaloXGQF5ARy1
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        client-authentication-method: POST
                        authorization-grant-type: authorization_code
                        scope: profile_nickname
                        client-name: Kakao
                        
                provider:
                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response
                    
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                        
jwt:
    
    secretKey: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNDbajtmxmzjaqorghadbr2333ktvlfwmtpdlmdjTMrmrwk626345257567dvksrmeo21579emfdmsdjEjgrptkfrjtdlsrkyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    
    access:
        expiration: 600
        header: Authorization
        
    refresh:
        expiration: 2592000
        header: RefreshToken
        




